### ISSUE TITLE
Generated MD5 passwords differ from online version in some cases

### ISSUE THREAD

**Issue by matofesi** [eterevsky/passwordgen#7] opened 2014-06-09 09:59 UTC
I've been using the other version of password generator extension together with online version but now I tried to use this extension as it's much nicer. Unfortunatelly there seems to be an error in MD5 password generation algorithm generating passwords that are different than in online version. After some trials I found that when the combination of password+domain generates password starting with 'A' it's wrong - online version (and all other versions I've tried) generates the same password but starting from the second character.
eg. for domain google.com with password of '1' (single character) this extension generates password of 'A1v0)iYu' while the online versions gives '1v0)iYu,'.

**Comment by eterevsky** [comment] 2014-06-09 10:58
I tried the online version and got `A1v0)iYu`. Here's a screenshot of my settings:
![pg](https://cloud.githubusercontent.com/assets/2182541/3215755/db260226-efc4-11e3-9dbc-93f5f98de3fd.png)

Could you please attach a screenshot of your settings?

**Comment by eterevsky** [comment] 2014-06-09 10:59
Just in case you're using some other online generator. Here's a link to this one: http://passwordgen.org.

**Comment by matofesi** [comment] 2014-06-09 11:04
Ummm... I've been using this online
http://www.passwordmaker.org/passwordmaker.html generator and I've got to
your extension from this page: http://www.passwordmaker.org/Google_Chrome
and I assumed that all extensions that are linked from there would result
in the same password beeing generated and the same password as the
PasswordMaker online generator.

m.

## 

Maciej J. Woloszyk, matofesi@gmail.com     "Rejoice. For Very Bad
tel. +48 501 033 410                   Things are about to happen."
JID:matofesi@gmail.com             Richard/Looking For Group

**Comment by eterevsky** [comment] 2014-06-09 11:09
I did try to be compatible with PasswordMaker, but this implementation does have a few differences. For instance, it includes an option "Use all selected character types in each password", which is incompatible with PM. On the other hand, passwordgen doesn't include HMAC and adding additional prefixes, path and so on.

**Comment by matofesi** [comment] 2014-06-09 11:12
Ok. Now I understand and I'll change all affected passwords to use your
extension. It would be nice to make guys at PasswordMaker to clearly state
that passwords generated by passwordgen might not be the same as the
passwordmaker - it would probably saved me some time if I knew ;)

m.

## 

Maciej J. Woloszyk, matofesi@gmail.com     "Rejoice. For Very Bad
tel. +48 501 033 410                   Things are about to happen."
JID:matofesi@gmail.com             Richard/Looking For Group

**Comment by eterevsky** [comment] 2014-06-09 11:15
I think I know what might have lead to this problem. 'A' is a first character in the set and binary hash might have been converted to a string in slightly different ways in PM and PG. I'll look into, though I am not sure, what would be a correct solution: if it is indeed my bug, and I fix it, I might break some passwords the current users of PG have.

In any case, thanks for letting me know about this issue.

**Comment by eterevsky** [comment] 2014-06-17 10:04
Closing as duplicate of #9.

**Closed as completed by eterevsky** 2014-06-17 10:04 UTC
